version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    AWS_ACCOUNT_ID: "116671358684"
    REPOSITORY_URI: "116671358684.dkr.ecr.us-east-1.amazonaws.com/backend-extrato"
    IMAGE_TAG: "latest"
    APP_DIR: "backend-extrato"

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - echo Login no ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build da aplicacao
      - |
        if [ -f gradlew ] && [ -f Dockerfile ]; then
          export APP_PATH="."
        elif [ -f "$APP_DIR/gradlew" ] && [ -f "$APP_DIR/Dockerfile" ]; then
          export APP_PATH="$APP_DIR"
        else
          echo "Nao foi possivel localizar gradlew e Dockerfile em . ou $APP_DIR"
          exit 1
        fi
      - echo APP_PATH=$APP_PATH
      - cd $APP_PATH
      - chmod +x gradlew
      - ./gradlew clean build
      - echo Build da imagem Docker
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Push da imagem
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Gerando imagedefinitions.json
      - printf '[{"name":"backend-extrato","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
