CREATE TABLE bill_payment_notification_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email VARCHAR(255) NOT NULL,
    reference_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_bill_payment_notification_log UNIQUE (user_email, reference_date)
);

CREATE INDEX idx_bill_payment_notification_log_user_email_reference_date
    ON bill_payment_notification_log(user_email, reference_date);
