CREATE TABLE mobile_push_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expo_push_token VARCHAR(255) NOT NULL,
    user_email VARCHAR(255),
    user_name VARCHAR(255),
    platform VARCHAR(32) NOT NULL,
    device_name VARCHAR(255),
    app_version VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mobile_push_subscription_token UNIQUE (expo_push_token)
);

CREATE INDEX idx_mobile_push_subscription_user_email
    ON mobile_push_subscription(user_email);
