INSERT INTO company_profile (
    user_email,
    legal_name,
    trade_name,
    cnpj,
    tax_regime,
    activity,
    state_registration,
    municipal_registration,
    opening_date,
    business_phone,
    business_email,
    website,
    contact_name,
    zip_code,
    street,
    number,
    complement,
    district,
    city,
    state,
    invoice_email,
    pix_key,
    main_bank,
    billing_notes,
    accountant_name,
    accountant_email,
    accountant_phone,
    payroll_notes,
    operation_notes,
    created_at,
    updated_at
)
SELECT
    'everton_ere93@hotmail.com',
    'EVERTON CARVALHO SILVA DESENVOLVIMENTO DE SOFTWARE LTDA',
    'EVERTON SILVA TEC',
    '31.951.466/0001-04',
    'Simples Nacional',
    'Desenvolvimento de programas de computador sob encomenda',
    NULL,
    NULL,
    '2018-11-06',
    '(11) 99824-1145',
    'developer@evertonsilva.io',
    NULL,
    'Everton Carvalho da Silva',
    '09450-000',
    'R Madalena Bracialli',
    '149',
    NULL,
    'Vila Lopes',
    'Rio Grande da Serra',
    'SP',
    'developer@evertonsilva.io',
    'developer@evertonsilva.io',
    'Itaú - agência 0691 - conta 99368-7',
    'Dados bancários extraídos da ficha cadastral da FCamara.',
    NULL,
    NULL,
    NULL,
    'Natureza jurídica atual: Limitada Unipessoal (ME).',
    'NIRE 35232777861. Capital social R$ 10.000,00. CNAE principal 62.01-5-01. Atividade secundária: reparação e manutenção de computadores e periféricos. Email antigo encontrado em documentos da Receita: everton_ere93@hotmail.com. Telefone fixo antigo encontrado em documentos da Receita: (11) 4820-3757.',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1
    FROM company_profile
    WHERE LOWER(user_email) = LOWER('everton_ere93@hotmail.com')
);
