CREATE TABLE user_data_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_email VARCHAR(255) NOT NULL,
    viewer_email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_data_access_owner_viewer UNIQUE (owner_email, viewer_email)
);

CREATE INDEX idx_user_data_access_owner_email ON user_data_access(owner_email);
CREATE INDEX idx_user_data_access_viewer_email ON user_data_access(viewer_email);
